apiVersion: batch/v1
kind: Job
metadata:
  name: mock-log-demo
  namespace: default
spec:
  template:
    metadata:
      name: mock-log-demo
    spec:
      restartPolicy: Never
      containers:
      - name: mock-log-demo
        image: registry.cn-hangzhou.aliyuncs.com/log-service/docker-log-test:latest
        command: ["/bin/mock_log"]
        args: ["--log-type=nginx", "--stdout=false", "--stderr=true", "--path=/var/log/nginx/access.log", "--total-count=1000000000", "--logs-per-sec=100"]
