filebeat.registry.path: /app/filebeat/registry

filebeat.inputs:
- type: filestream
  id: 100
  enabled: true
  paths:
    - /var/log/mock-log/*
    - /var/log/mock-log-1/*

output.kafka:
  hosts: ["192.168.1.11:7092"]
  topic: "filebeat_bench"
  required_acks: 1
  compression: snappy

logging.level: error
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0664
  rotateeverybytes: 52428800